config/routes.rb
HenParty::Application.routes.draw do

  root to: "welcome#homepage"

  devise_for :users, :skip => [:registrations]
  
  resources :parties, :except => [:new] do
    resources :invitations, :only => [:new, :create]
  end
  post 'parties/new' => 'parties#new', as: 'new_party'

  get 'parties/:party_id/plan' => 'plan#index', :as => 'plan_party'
  get 'parties/:party_id/plan/itinerary' => 'plan#itinerary', :as => 'plan_itinerary'

  post 'parties/:party_id/plan/product_search' => 'plan#product_search', :as => 'products_to_plan_party'
  post 'parties/:party_id/plan/accommodation_search' => 'plan#accommodation_search', :as => 'accommodation_to_plan_party'

  get 'join/:token' => 'responses#new', :as => 'join_party'
  post 'join/:token' => 'responses#create', :as => 'save_party_response'

  

end

app/models/party.rb
class Party < ActiveRecord::Base

	belongs_to :user, dependent: :destroy

	has_many :budgets, :dependent => :destroy
	has_many :date_options, :dependent => :destroy
	has_many :participants, :dependent => :destroy

	validates :name, :presence => :true
	
	accepts_nested_attributes_for :budgets, allow_destroy: true, reject_if: lambda {|attributes| attributes['amount'].blank?}
	accepts_nested_attributes_for :date_options, allow_destroy: true, reject_if: lambda {|attributes| attributes['start_date'].blank?}
	accepts_nested_attributes_for :participants, allow_destroy: true, reject_if: lambda {|attributes| attributes['email'].blank?}

	def assign_chief_hen(user)
		self.user = user
		user.chief_hen = true
		user.save and save
	end
	
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :authenticate_user!, except: [:new,
                                              :create]
  before_action :set_party, only: [:show,
                                   :edit,
                                   :update,
                                   :destroy]
  helper_method :party_and_user_errors

  # GET /parties
  # GET /parties.json
  def index
    @parties = current_user.parties.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find params[:id]
    if !current_user.parties.include?(@party)
      render :text => "<h1>Sorry, you don't have access to this party.</h1>", :status => '404', :layout => true
    end
  end

  # POST /parties/new
  def new
    party_name = { name: "#{params[:party][:brides_name]}'s Hen Party" }
    @party = Party.new(party_name)
    @user = User.new
    1.times do
      question = @party.budgets.build
      date_option = @party.date_options.build
      participant = @party.participants.build
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find params[:id]
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save && @party.save
        @party.assign_chief_hen(@user)
        sign_in(@user)
        begin
          PartyInvitation.create_party_confirmation(@user, @party).deliver!
        rescue
        end
        format.html { redirect_to edit_party_path(@party), notice: 'Party was successfully created.' }
        format.json { render action: 'edit', status: :created, location: @party }
      else
        format.html { render action: 'new' }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name,
                                    budgets_attributes:      [:id,
                                                              :_destroy,
                                                              :amount],
                                    participants_attributes: [:id,
                                                              :_destroy,
                                                              :email,
                                                              :first_name,
                                                              :last_name,
                                                              :konnection],
                                    date_options_attributes: [:id,
                                                              :_destroy,
                                                              :start_date,
                                                              :end_date])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def party_and_user_errors
      @party.errors.full_messages + @user.errors.full_messages
    end

end

app/helpers/parties_helper.rb
module PartiesHelper

  def format_price(page)
    total = number_to_currency((page.price + page.pnp), precision: 2)

    if page.pnp > 0
      pnp = number_to_currency(page.pnp, precision: 2)
    else
      pnp = "free P&P"
    end

    "#{total} (inc. #{pnp})"
  end

end

app/views/parties/_budget_fields.html.erb
<fieldset>
  <div class="form-group">
  	<%= f.label :amount, "Budget Amount" %>
  	<%= f.text_field :amount %>
  	<%= f.hidden_field :_destroy %>
  	<%= link_to "remove", '#', class: "remove_fields" %>
  </div>
</fieldset>
 

app/views/parties/_contact_detail_fields.html.erb
<fieldset>
  <div class="form-group">
    <%= f.label :address_line_1, "Address line 1", class: 'sr-only' %>
    <%= f.text_field :address_line_1, class: 'form-control', placeholder: 'Address line 1' %>
  </div>
  <div class="form-group">
    <%= f.label :address_line_2, "Address line 2", class: 'sr-only' %>
    <%= f.text_field :address_line_2, class: 'form-control', placeholder: 'Address line 2' %>
  </div>
  <div class="form-group">
    <%= f.label :address_town, "Address town", class: 'sr-only' %>
    <%= f.text_field :address_town, class: 'form-control', placeholder: 'Town' %>
  </div>
  <div class="form-group">
    <%= f.label :address_post_code, "Address post code", class: 'sr-only' %>
    <%= f.text_field :address_post_code, class: 'form-control', placeholder: 'Post code' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_mobile, "Phone mobile", class: 'sr-only' %>
    <%= f.text_field :phone_mobile, class: 'form-control', placeholder: 'Mobile number' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_home, "Phone home", class: 'sr-only' %>
    <%= f.text_field :phone_mobile, class: 'form-control', placeholder: 'Home number' %>
  </div>
</fieldset>

app/views/parties/_date_option_fields.html.erb
<fieldset>
  <%= f.label :start_date, "Start Date" %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date, "End Date" %>
  <%= f.date_field :end_date %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/parties/_form.html.erb
<%= form_for @party, html: { class: 'form-inline', role: 'form' } do |f| %>

  <div class="flex-grid">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', size: 50 %>
    </div>
  </div>

<div class="flex-grid">
  <div class="form-group">
    <%= f.fields_for :participants do |builder| %>
      <%= render 'participant_fields', f: builder %><br/>
    <% end %>
    <%= link_to_add_fields "Add Hen", f, :participants %> 
  </div><br/>
</div>
<br/>

<div class="flex-grid">
    <div class="form-group">
      <%= f.fields_for :budgets do |builder| %>
        <%= render 'budget_fields', f: builder %><br/>
      <% end %>
      <%= link_to_add_fields "Add Budget Options", f, :budgets %>
    </div>
</div>
<br/>

<div class="flex-grid">
  <div class="form-group">
    <%= f.fields_for :date_options do |builder| %>
      <%= render 'date_option_fields', f: builder %><br/>
    <% end %>
    <%= link_to_add_fields "Add Date Options", f, :date_options %> <br/>
  </div>
</div>
<br/>

<div class="btn-group">
  <div class="actions" >
    <%= f.submit class: 'btn btn-default btn-pink' %>
    <%= link_to 'Back to Party Details', party_path(@party), class: 'btn btn-default' %>
  </div>
</div>
<br/>

<% end %>

app/views/parties/_participant_fields.html.erb
<fieldset>
  <div class="form-group">
    <%= f.label :first_name, "First name", class: 'sr-only' %>
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, "Last name", class: 'sr-only' %>
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name' %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Email address", class: 'sr-only' %>
    <%= f.email_field :email, class: 'form-control', placeholder: 'Email address' %>
  </div>
  <div class="form-group">
    <%= f.label :konnection, "Connection to the Bride", class: 'sr-only' %>
    <%= f.text_field :konnection, class: 'form-control', placeholder: 'Connection to the Bride' %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :_destroy %>
    <%= link_to "remove", '#', class: "remove_fields" %>
  </div>
</fieldset>

app/views/parties/_user_fields.html.erb
<fieldset>
  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div><br/>
</fieldset>

app/views/parties/edit.html.erb
<p><%= link_to 'Back to Party Details', party_path(@party), class: 'btn btn-default btn-lg' %></p>



<h1>Add options to your party</h1>

<%= render 'form' %>

<br/>
<br/>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <thead>
    <tr>
      <th>Name of party</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Party', new_party_path %>

app/views/parties/invitation.html.erb
<h1>Invite the hens to <%= @party.name %></h1>
<p>
  Send all the hens an email, you write the message and we'll add
  a special link for them to join your hen party.
</p>
<%= form_for :invitation, url: send_party_invitations_path,
                          html: { role: 'form' } do |f| %>
  
  <div class='form-group'>
    <%= f.label :subject %><br />
    <%= f.text_field :subject,
                     :placeholder => "#{@party.name}, it is time to celebrate!",
                     :autofocus => true,
                     :class => "form-control" %>
  </div>
  <div class='form-group'>
    <%= f.label :message %><br />
    <%= f.text_area :message,
                   :value => render('draft'),
                   :class => "form-control",
                   :rows => 8 %>
  </div>

  <div class='form-group'>
    <%= f.submit 'Send invitations', :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/parties/itinerary.html.erb
<h1>This is the plan for <%= @party.name %></h1>

app/views/parties/join.html.erb
<h1>Welcome to <%= @party.name %></h1>

<%= form_for :response, url: save_party_response_path, html: { role: 'form' } do |f| %>
  
  <div class="well">
    <h3>Date options</h3>
    <% @party.date_options.each do |date_option| %>
      <div class="form-group">
        <%= label_tag "#{l date_option.start_date} - #{l date_option.end_date}" %>
        &nbsp;&nbsp;&nbsp;
        <%= check_box_tag 'response[date_option_ids][]', date_option.id, false, id: "date_option_#{date_option.id}" %>
        <%= label_tag "I can make this date" %>
      </div>
    <% end %>
  </div>

  <div class="well">
    <h3>Budget options</h3>
    <% @party.budgets.each do |budget_option| %>
      <div class="form-group">
        <%= label_tag "#{number_to_currency budget_option.amount}" %>
        &nbsp;&nbsp;&nbsp;
        <%= check_box_tag 'response[budget_option_ids][]', budget_option.id, false, id: "budget_option_#{budget_option.id}" %>
        <%= label_tag "I can afford this budget" %>
      </div>
    <% end %>
  </div>

  <div class='form-group'>
    <%= f.submit 'Join the party', :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/parties/new.html.erb
<%= form_for(@party) do |f| %>
  <% if party_and_user_errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party_and_user_errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% party_and_user_errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex-grid">
    <div>
      <div class="well">
        <div class="form-group">
          <%= f.label :name, 'Name your hen party' %><br>
          <%= f.text_field :name, class: "form-control", placeholder: "Sam's Hen Party" %>
        </div>
        <div>
          <ul>
            <li>Three great things</li>
            <li>about organising a hen party</li>
            <li>with Hen Party App</li>
          </ul>
        </div>
      </div>
    </div>

    <div>
      <div class="well">
        <h4>Sign up</h4>
        
        <%= fields_for @user do |user_f| %>
          <div class="form-group">
            <%= user_f.label :first_name, class: 'sr-only' %>
            <%= user_f.text_field :first_name, class: "form-control", placeholder: 'First name'  %>
          </div>
          <div class="form-group">
            <%= user_f.label :last_name, class: 'sr-only' %>
            <%= user_f.text_field :last_name, class: "form-control", placeholder: 'Last name' %>
          </div>
          <div class="form-group">
            <%= user_f.label :email, class: 'sr-only' %>
            <%= user_f.email_field :email, class: "form-control", placeholder: 'Email address' %>
          </div>
          <div class="form-group">
            <%= user_f.label :password, class: 'sr-only' %>
            <%= user_f.password_field :password, class: "form-control", placeholder: 'Password' %>
          </div>
          <div class="form-group">
            <%= user_f.label :password_confirmation, class: 'sr-only' %>
            <%= user_f.password_field :password_confirmation, class: "form-control", placeholder: 'Password confirmation' %>
          </div>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Party', class: 'btn btn-default btn-lg sign-up' %>
      </div>
    </div>
  </div>
<% end %>

app/views/parties/show.html.erb
  <div class="btn-group">
    <%= link_to 'Add Options', edit_party_path(@party), class: 'btn btn-default btn-lg' %>
      <% if @party.participants.count > 0 %>
       <%= link_to 'Invite Hens', new_party_invitation_path(@party), class: 'btn btn-default btn-lg' %>
      <% end %>
      <%= link_to 'Plan this party', plan_party_path(@party), class: 'btn btn-default btn-lg' %>
  </div>

  <h1><%=@party.name.capitalize%> </h1>
  
  <div class="flex-grid">
		<div>
      <h2>Budgets</h2>
				<% @party.budgets.each do |f| %>
					<div style="font-size: 120%;">	£<%= f.amount %></div>
				<% end %>
    </div>

   <div>
      <h2>Dates</h2>
				<% @party.date_options.each do |f| %>
					<div style="font-size: 120%;"><%= f.start_date.strftime('%a %d %b %Y') %> &mdash; <%= f.end_date.strftime('%a %d %b %Y') %></div>
				<% end %>
    </div>
  </div>
  <div class="flex-grid">
    <div>
      <h2>Hens</h2>
        <% @party.participants.each do |f| %>
          <p><%= f.email %> | <%= [f.first_name, f.last_name].join ' ' %> | <%= f.konnection %></p>
        <% end %>   
    </div>
  	<div>
      <h2>Your contact details</h2>
        <p><%= [current_user.first_name, current_user.last_name].join ' ' %>
        <p><%= current_user.email%></p>
        <p>074473567553</p>
    </div>
  </div>
</div>