config/routes.rb
HenParty::Application.routes.draw do

  root to: "welcome#homepage"

  devise_for :users, :skip => [:registrations]
  
  resources :parties, :except => [:new] do
    resources :invitations, :only => [:new, :create]
  end
  post 'parties/new' => 'parties#new', as: 'new_party'

  get 'parties/:party_id/plan' => 'plan#index', :as => 'plan_party'
  get 'parties/:party_id/plan/itinerary' => 'plan#itinerary', :as => 'plan_itinerary'

  post 'parties/:party_id/plan/product_search' => 'plan#product_search', :as => 'products_to_plan_party'
  post 'parties/:party_id/plan/accommodation_search' => 'plan#accommodation_search', :as => 'accommodation_to_plan_party'

  get 'join/:token' => 'responses#new', :as => 'join_party'
  post 'join/:token' => 'responses#create', :as => 'save_party_response'

  

end

app/controllers/invitations_controller.rb
require 'github/markdown'

class InvitationsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_party

  # GET /parties/1/invitation
  def new
  end

  # POST /parties/1/invitations
  def create
    subject = params[:party_invitations][:subject]
    message = GitHub::Markdown.render(params[:party_invitations][:message].html_safe)

    participants = @party.participants
    
    participants.each do |participant|
      begin
        PartyInvitation.invitation_email(participant, subject, message).deliver!
      rescue
      end
    end

    redirect_to @party, notice: 'Invitations successfully sent.'
  end

  private

    def set_party
      @party = Party.find(params[:party_id])
    end

    def invitation_params
      params.require(:invitation).permit(:subject, :message)
    end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_draft_invitation.html.erb
Hello lovely ladies,

I hope you are all well.

Our darling friend (Bride's name) is getting married. And what better way to
send her into married life than with an awesome She-ra themed hen party!

The bride would love to have you with her to celebrate this very big time in
her life.

As you see, there is a link at the bottom of this email. This will take you
to the Hen Party App, were you will be asked to complete a form specifying
when you are free and your budget.

This will help me get the wheels in motion.
I look forward to getting your feedback.

All the best,

<%= current_user.first_name %>, Chief Hen

app/views/invitations/new.html.erb
<h1>Invite the hens to <%= @party.name %></h1>

<div class='col-lg-9'>
<br/>
<br/>
<p>
  Send all the hens an email, you write the message and we'll add
  a special link for them to join your hen party.
</p>
<%= form_for :party_invitations, url: party_invitations_path,
                          html: { role: 'form' } do |f| %>
  
  <div class='form-group'>
    <%= f.label :subject %><br />
    <%= f.text_field :subject,
                     :value => "#{@party.name} - it's time to celebrate!",
                     :autofocus => true,
                     :class => "form-control" %>
  </div>
  <div class='form-group'>
    <%= f.label :message %><br />
    <%= f.text_area :message,
                    :value => render('draft_invitation'),
                    :class => "form-control",
                    :rows => 8 %>
  </div>
  <br/>
  <div class="btn-group">
    <div class='form-group'>
      <%= f.submit 'Send invitations', :class => 'btn btn-default btn-pink' %>
      <%= link_to 'Back to Party Details', party_path(@party), class: 'btn btn-default' %>
    </div>
   
  </div>
  <br/>
  <br/>

<% end %>