config/routes.rb
HenParty::Application.routes.draw do

  root to: "welcome#homepage"

  devise_for :users, :skip => [:registrations]
  
  resources :parties, :except => [:new] do
    resources :invitations, :only => [:new, :create]
  end
  post 'parties/new' => 'parties#new', as: 'new_party'

  get 'parties/:party_id/plan' => 'plan#index', :as => 'plan_party'
  get 'parties/:party_id/plan/itinerary' => 'plan#itinerary', :as => 'plan_itinerary'

  post 'parties/:party_id/plan/product_search' => 'plan#product_search', :as => 'products_to_plan_party'
  post 'parties/:party_id/plan/accommodation_search' => 'plan#accommodation_search', :as => 'accommodation_to_plan_party'

  get 'join/:token' => 'responses#new', :as => 'join_party'
  post 'join/:token' => 'responses#create', :as => 'save_party_response'

  

end

app/views/party_invitation/create_party_confirmation.html.erb
<h3>Congratulations!</h3>
<p>Hi <%= @user.first_name %></p>
<p>You have just created <%= @party.name %>!</p>
<p>
  Follow this is link to plan your hen party:<br />
  <%= link_to "Plan #{@party.name}", party_url(@party) %>
</p>
<p>
  Happy planning<br />
  from the Hen Party App Team
</p>

app/views/party_invitation/invitation_email.html.erb
<%= @message.html_safe %>
<p>
  Your special link to join the party:<br />
  <%= join_party_url token: @participant.token %>
</p>

app/views/party_invitation/response_confirmation.html.erb
<h2>You have joined <%= @participant.party.name %></h2>
<p>Here is confirmation of your response:</p>
<h3>Dates you can make</h3>
<ul>
  <% @response.date_options.each do |date_option| %>
    <li><%= "#{l date_option.start_date} - #{l date_option.end_date}" %></li>
  <% end %>
</ul>
<h3>Budgets you can afford</h3>
<ul>
  <% @response.budgets.each do |budget| %>
    <li><%= number_to_currency budget.amount %></li>
  <% end %>
</ul>