config/routes.rb
HenParty::Application.routes.draw do

  root to: "welcome#homepage"

  devise_for :users, :skip => [:registrations]
  
  resources :parties, :except => [:new] do
    resources :invitations, :only => [:new, :create]
  end
  post 'parties/new' => 'parties#new', as: 'new_party'

  get 'parties/:party_id/plan' => 'plan#index', :as => 'plan_party'
  get 'parties/:party_id/plan/itinerary' => 'plan#itinerary', :as => 'plan_itinerary'

  post 'parties/:party_id/plan/product_search' => 'plan#product_search', :as => 'products_to_plan_party'
  post 'parties/:party_id/plan/accommodation_search' => 'plan#accommodation_search', :as => 'accommodation_to_plan_party'

  get 'join/:token' => 'responses#new', :as => 'join_party'
  post 'join/:token' => 'responses#create', :as => 'save_party_response'

  

end

app/controllers/plan_controller.rb
class PlanController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_party
  before_action :set_responses, only: [:index,
                                       :accommodation_search,
                                       :product_search]
  before_action :get_best_price_pages

  def index
  end

  def product_search
    # search_terms = params[:product][:search]
    # @product_search_results = get_product_search_results(search_terms)
    # render 'plan'
    redirect_to plan_party_path(@party)
  end

  def accommodation_search
    search_terms = params[:accommodation]
    @check_in = l(search_terms[:arrival_date].to_date, format: :uk)
    @check_out = l(search_terms[:departure_date].to_date, format: :uk)
    @accommodation_results = get_accommodation_list(search_terms)
    render 'index'
  end

  def itinerary
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:party_id])
    end

    def set_responses
      @participants = @party.participants
      @budget_responses = budget_responses
      @budget_options = @party.budgets
      @date_responses = date_responses
      @date_options = @party.date_options
    end

    def budget_responses
      # @budget_responses = @party.budgets.inject() { |totals, budget| totals[budget.amount] = budget.participants.size }
      @party.participants.each do |party_participant|
        unless party_participant.response.nil? || party_participant.response.budgets.nil? 
          party_participant.response.budgets.each do |budget_response|
            @budget_responses.nil? ? @budget_responses = [budget_response.amount] : @budget_responses << budget_response.amount
          end
        end
      end
      @budget_responses
    end 

    def date_responses
      # @budget_responses = @party.budgets.inject() { |totals, budget| totals[budget.amount] = budget.participants.size }
      @party.participants.each do |party_participant|
        unless party_participant.response.nil? || party_participant.response.date_options.nil? 
          party_participant.response.date_options.each do |date_response|
            @date_responses.nil? ? @date_responses = [date_response.id] : @date_responses << date_response.id
          end
        end
      end
      @date_responses
    end

    def get_best_price_pages
      products = { kit:            '02aecf7f1570ea714fdc00bf581ee66c',
                   l_plates:       '18688049702bbfcc4f90602b57191970',
                   balloons:       '70e8dc10e22d680e1e1525e240b9319e',
                   truth_or_dare:  'd7bba5ce3d121cf37e63cf47891038cc',
                   penis_straws:   'a08bc320d65897ca6afdc1d0180c2ea9',
                   chocolate:      'e356c0566b45d9dd4627af77aa679192' }
                   # memento_book:   '1c2745fac7f8117db364e0ddca0f1424',
                   # shera:          'ff1cb21c78cfcaaddf58e445d2f24b56',
                   # gay_bf:         '1f96b711b43040e94ebaa0ff42ac0195',
      begin
        @best_price_pages = best_pages(products.values)
      rescue
        @best_price_pages = false
      end
    end

    def best_pages(product_ids)
      products = product_ids.map { |id| product_details(id) }
      products.inject([]) do |best_pages, product|
        best_pages << product.pages.min_by { |page| page.price + page.pnp  }
      end
    end

    def get_product_search_results(search_term)
      search_results = invisible_hand_api.products(
                                     :query => search_term,
                                     :sort => "popularity",
                                     :order => "desc",
                                     :size => "3")
      best_pages(search_results.map { |product| product.id })
    end

    def invisible_hand_api
      @invisible_hand_api ||= InvisibleHand::API.new(
                                :app_id => ENV['INVISIBLE_HAND_APP_ID'],
                                :app_key => ENV['INVISIBLE_HAND_APP_KEY'],
                                :region => 'uk')
    end

    def product_details(product_id)
      invisible_hand_api.product(product_id)
    end

    def expedia_api
      @expedia_api ||= Expedia::Api.new
    end

    def get_accommodation_list(search_terms)
      api_request = {
        numberOfResults:  20,
        countryCode:      'GB',
        city:             search_terms[:city],
        propertyCategory: search_terms[:property_category],
        arrivalDate:      l(search_terms[:arrival_date].to_date, format: :us),
        departureDate:    l(search_terms[:departure_date].to_date, format: :us),
        maxRate:          search_terms[:max_rate] * 2
      }
      api_response = expedia_api.get_list(api_request)
      accommodation_list = api_response.body["HotelListResponse"]["HotelList"]["HotelSummary"]

      accommodation_list.reject! do |accommodation|
        rooms_available = accommodation['RoomRateDetailsList']['RoomRateDetails']['currentAllotment']
        room_occupancy = accommodation['RoomRateDetailsList']['RoomRateDetails']['quotedRoomOccupancy']
        rooms_available == 0 || room_occupancy * rooms_available < search_terms[:guests].to_i 
      end
      accommodation_list.take(5)
    end

end

app/helpers/plan_helper.rb
module PlanHelper
end

app/views/plan/_accommodation_results.html.erb
<ul class="media-list">
  <% @accommodation_results.each do |result| %>
    <li class="media">
      <a class="pull-left" href="#">
        <%= image_tag "http://images.travelnow.com#{result['thumbNailUrl']}", class: 'media-object' %>
      </a>
      <div class="media-body">
        <% rooms_link_text = "See " + result['RoomRateDetailsList']['RoomRateDetails']['currentAllotment'].to_s + " rooms available" %>
        <% room_link = "http://www.expedia.co.uk/h" + result['RoomRateDetailsList']['RoomRateDetails']['expediaPropertyId'].to_s + ".Hotel-Information?chkin=" + @check_in + "&chkout=" + @check_out + "&hiddenDateless=true#roomsAndRates" %>
        <div class="pull-right"><%= link_to rooms_link_text, room_link, class: 'btn btn-default btn-md' %></div>
        <h4 class="media-heading"><%= result['name'].html_safe %></h4>
        <p>
          <%= image_tag result['tripAdvisorRatingUrl'] %>
          <%= result['tripAdvisorReviewCount'] %> reviews
        </p>
        <h5>From <%= number_to_currency((result['lowRate'] / result['RoomRateDetailsList']['RoomRateDetails']['quotedRoomOccupancy']), precision: 2) %> per person per night</h5>
      </div>
    </li>
  <% end %>
</ul>

app/views/plan/_best_price_products.html.erb
<div class="row">
  <% @best_price_pages.each do |page| %>
    <div class="col-sm-6 col-md-4" style="margin-bottom: 1em;">
      <div class="thumbnail" style="min-height: 565px;">
        <%= image_tag page.image_url, width: '300px', height: '200px', class: 'img-rounded' %>
        <div class="caption">
          <h3><%= page.title %></h3>
          <p>
            <dl>
              <dt>Retailer</dt>
              <dd><%= page.retailer_name %></dd>
            </dl>
            <h4><%= format_price(page) %></h4>
          </p>
          <p>
            <%= link_to 'Buy now', page.original_url, class: 'btn btn-default btn-md' %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/plan/_product_search_results.html.erb
<% @product_search_results.each do |page| %>
  <div class="row">
    <div class="col-sm-6 col-md-4" style="margin-bottom: 1em;">
      <div class="thumbnail" style="min-height: 53px;">
        <%= image_tag page.image_url, width: '300px', height: '200px', class: 'img-rounded' %>
        <div class="caption">
          <h3><%= page.title %></h3>
          <p>
            <dl>
              <dt>Retailer</dt>
              <dd><%= page.retailer_name %></dd>
            </dl>
            <h4><%= format_price(page) %></h4>
          </p>
          <p>
            <%= link_to 'Buy now', page.original_url, class: 'btn btn-default btn-md' %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/plan/index.html.erb
<div class="btn-group">
  <%= link_to 'View Party Details', party_path(@party), class: 'btn btn-default btn-lg' %>
    <% if @party.participants.count > 0 %>
      <%= link_to 'Itinerary', plan_itinerary_path(@party), class: 'btn btn-default btn-lg' %>
    <% end %>
</div>

<h1>Plan <%= @party.name %></h1>
<div class="flex-grid">
  <div class='chart transbox'>
    <h2>Budget Results</h2>
    <% if @budget_options.nil? || @budget_responses.nil? %>
      <p>No budgets voted for yet!</p>
    <% else %>
      <% @budget_options.each do | budget | %>
        <p>£<%= budget.amount %></p>
        <div style="width: <%=@budget_responses.count(budget.amount) + 10%>%;"><%= @budget_responses.count(budget.amount) %></div><br/>
      <%end %>
    <%end%>
  </div>
  <div class='chart transbox'>
    <h2>Date Results</h2>
    <% if @date_options.nil? || @date_responses.nil? %>
      <p>No dates voted for yet!</p>
    <% else %>
      <% @date_options.each do | date_o | %>
        <p><%= date_o.start_date.strftime('%d %b %Y') %> - <%= date_o.end_date.strftime('%d %b %Y') %></p>
        <div style="width: <%=@date_responses.count(date_o.id) + 10%>%;"><%= @date_responses.count(date_o.id) %></div><br/>
      <%end %>
    <%end%>
  </div>
</div>

<div class="flex-grid">
  <div>
    <h2>Search for accommodation with Expedia</h2>
    <%= form_for :accommodation, url: accommodation_to_plan_party_path, html: { class: 'form-inline', role: 'form' } do |f| %>
      <div class="form-group">
        <%= f.label :city, class: 'sr-only' %>
        <%= f.text_field :city, class: "form-control", placeholder: 'City', size: 18 %>
      </div>
      <div class="form-group">
        <%= f.label :guests, 'No. of people', class: 'sr-only' %>
        <%= f.text_field :guests, class: "form-control", placeholder: 'No. of people', size: 15 %>
      </div>
      <div class="form-group">
        <%= f.label :max_rate, 'Price per person', class: 'sr-only' %>
        <%= f.text_field :max_rate, class: "form-control", placeholder: 'Price per person', size: 15 %>
      </div>
      <div class="form-group">
        <%= f.label :property_category, 'Type', class: 'sr-only' %>
        <%= f.select :property_category, options_for_select(
                                            [["Hotel", 1],
                                            ["Vacation Rental", 4],
                                            ["Bed & Breakfast", 5]],
                                            "Hotel"),
                                          {},
                                          class: 'form-control' %>
      </div>
      <br /><br />
      <div class="form-group">
        <%= f.label :arrival_date, 'Check in' do %>
          Check in <%= f.date_field :arrival_date, class: 'form-control' %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :departure_date, 'Check out' do %>
          Check out <%= f.date_field :departure_date, class: "form-control" %>
        <% end %>
      </div>
      <br /><br />
      <%= f.submit 'Find accommodation', class: "btn btn-default" %>
    <% end %>
    <br />
    <% if @accommodation_results %>
      <%= render 'accommodation_results' %>
    <% end %>
  </div>
</div>

<div class="flex-grid">
  <div>
    <h2>Best prices to get your party started</h2>
    <% if @product_search_results %>
      <%= render 'product_search_results' %>
    <% end %>
    <%= form_for :product, url: products_to_plan_party_path, html: { class: 'form-inline', role: 'form' } do |f| %>
      <div class="form-group">
        <%= f.label :search, class: 'sr-only' %>
        <%= f.text_field :search, class: "form-control", size: 70, placeholder: "feather bowers, balloons, etc." %>
      </div>
      <%= f.submit 'Search', class: "btn btn-default" %>
    <% end %>
    <% if @best_price_pages %>
      <h3>Some suggestions for you</h3>
      <%= render 'best_price_products' %>
    <% end %>
  </div>
</div>

app/views/plan/itinerary.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HenParty" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="btn-group">
      <%= link_to 'Back to Plan', plan_party_path(@party), class: 'btn btn-default btn-lg' %>
    </div>
    <h1>Here is the itinerary for <%= @party.name %></h1>
    <div class="flex-grid">
      <div class='chart transbox'>
        <h2>Destination </h2></br>
          <strong>We are heading to ... (drumroll)</strong></br>
          <strong>Manchester!</strong>
      </div>
      <div class='chart transbox'>
        <h2>Budget</h2></br>
          <strong>The budget for the party is £250</strong></br>
          <strong>This includes hotel and activities. Extra will be needed for drinks.</strong>
      </div>
      <div class='chart transbox'>
        <h2>Date</h2></br>
          <strong>The date has been set!</strong></br>
          <strong>We are heading out on the 15th of Feb, returning on the 17th!</strong>
      </div>
       <div class='chart transbox'>
        <h2>Keep in touch</h2></br>
          <address>
            <strong>Sam Harris</strong><br>
            <a href="mailto:#">samantha.s.harris@gmail.com</a>
            <abbr title="Phone">P:</abbr> 07754873927
          </address>
      </div>
    </div>

    <div class="flex-grid">
      <div>
        <h2>Where we will be staying... </h2>
        <div class="media">
          <a class="pull-left" href="#">
           <img alt="10959 27 t" class="media-object" src="http://images.travelnow.com/hotels/1000000/20000/11000/10959/10959_27_t.jpg">
          </a>
          <div class="media-body">
            <a class="pull-right">
              <address>
                <strong>The Midland - Manchester</strong><br>
                Peter Street,<br>
                Manchester,<br>
                England<br>
                M60 2DS<br>
                United Kingdom<br>
                <abbr title="Phone">P:</abbr> 0203 027 8675
              </address>
            </a>
              <h4 class="media-heading">The Midland - Manchester</h4>
              <p>
                <img alt="4.5 12345 4" src="http://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-12345-4.gif">
                1889 reviews
              </p>
          </div>
        </div>
      </div>
    </div>

    <div class="flex-grid">
      <div>
        <h2>For the people leaving from London... Trains </h2>
        <div class="media">
          <div class="media-body center">
            <h4> Trains leaving from London Euston </h4>
            <strong> Train times: Most of use will be getting the 18:00, but here are the options.</strong>
            <p> <img src="https://raw.github.com/Harrisam/hen_party/master/app/assets/images/trains.png"></p>
          </div>
        </div>
      </div>
    </div>

    <div class="flex-grid">
      <div>
        <h2>And finally... a little map: </h2>
        <div class="media">
          <div class="media-body center">
            <h4> Journey from the train station to the hotel. </h4>
            <strong> We will be meeting in the hotel bar for drinks before dinner... Gettign ready to surprise the bride</strong>
            <p><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=d&amp;source=s_d&amp;saddr=Manchester+Piccadilly,+Manchester&amp;daddr=The+Midland,+Manchester,+Peter+Street,+Manchester&amp;hl=en&amp;geocode=FQAAMAMdhPXd_yGX_bQ_QXabLSnP9B0FlrF7SDGX_bQ_QXabLQ%3BFWH_LwMdWr7d_yENBDIUFPfa9CkLuYFzwrF7SDENBDIUFPfa9A&amp;aq=0&amp;oq=The+Midland+-+Manchester&amp;sll=53.477376,-2.230908&amp;sspn=0.009207,0.021458&amp;mra=ls&amp;ie=UTF8&amp;t=m&amp;ll=53.478265,-2.237692&amp;spn=0.008939,0.018282&amp;z=15&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?f=d&amp;source=embed&amp;saddr=Manchester+Piccadilly,+Manchester&amp;daddr=The+Midland,+Manchester,+Peter+Street,+Manchester&amp;hl=en&amp;geocode=FQAAMAMdhPXd_yGX_bQ_QXabLSnP9B0FlrF7SDGX_bQ_QXabLQ%3BFWH_LwMdWr7d_yENBDIUFPfa9CkLuYFzwrF7SDENBDIUFPfa9A&amp;aq=0&amp;oq=The+Midland+-+Manchester&amp;sll=53.477376,-2.230908&amp;sspn=0.009207,0.021458&amp;mra=ls&amp;ie=UTF8&amp;t=m&amp;ll=53.478265,-2.237692&amp;spn=0.008939,0.018282&amp;z=15" style="color:#0000FF;text-align:left">View Larger Map</a></small></p>
          </div>
        </div>
      </div>
    </div>

  </body>  